./Solution.py BOOK A0 1
./Solution.py CANCEL A0 1
./Solution.py BOOK A0 1
./Solution.py BOOK A0 1
./Solution.py BOOK A1 1
./Solution.py BOOK A2 4
./Solution.py BOOK A5 1
./Solution.py BOOK A6 3
./Solution.py BOOK A8 1
./Solution.py BOOK U1 1
